//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_CW_8392.UI.SwipeCollection {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Terminal", Namespace="http://schemas.datacontract.org/2004/07/CP_CW_8392.BLL.Models")]
    [System.SerializableAttribute()]
    public partial class Terminal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CP_CW_8392.UI.SwipeCollection.Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CP_CW_8392.UI.SwipeCollection.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/CP_CW_8392.BLL.Models")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waiting = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProcess = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finished = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Swipe", Namespace="http://schemas.datacontract.org/2004/07/CP_CW_8392.BLL.Models")]
    [System.SerializableAttribute()]
    public partial class Swipe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAdddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SwipeDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectionField, value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAdddress {
            get {
                return this.IPAdddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAdddressField, value) != true)) {
                    this.IPAdddressField = value;
                    this.RaisePropertyChanged("IPAdddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SwipeDateTime {
            get {
                return this.SwipeDateTimeField;
            }
            set {
                if ((this.SwipeDateTimeField.Equals(value) != true)) {
                    this.SwipeDateTimeField = value;
                    this.RaisePropertyChanged("SwipeDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SwipeCollection.ISwipeCollectionService")]
    public interface ISwipeCollectionService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISwipeCollectionService/StartCollectingSwipes")]
        void StartCollectingSwipes();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISwipeCollectionService/StartCollectingSwipes")]
        System.Threading.Tasks.Task StartCollectingSwipesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwipeCollectionService/GetStatus", ReplyAction="http://tempuri.org/ISwipeCollectionService/GetStatusResponse")]
        CP_CW_8392.UI.SwipeCollection.Terminal[] GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwipeCollectionService/GetStatus", ReplyAction="http://tempuri.org/ISwipeCollectionService/GetStatusResponse")]
        System.Threading.Tasks.Task<CP_CW_8392.UI.SwipeCollection.Terminal[]> GetStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwipeCollectionService/GetAllSwipes", ReplyAction="http://tempuri.org/ISwipeCollectionService/GetAllSwipesResponse")]
        CP_CW_8392.UI.SwipeCollection.Swipe[] GetAllSwipes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwipeCollectionService/GetAllSwipes", ReplyAction="http://tempuri.org/ISwipeCollectionService/GetAllSwipesResponse")]
        System.Threading.Tasks.Task<CP_CW_8392.UI.SwipeCollection.Swipe[]> GetAllSwipesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISwipeCollectionServiceChannel : CP_CW_8392.UI.SwipeCollection.ISwipeCollectionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SwipeCollectionServiceClient : System.ServiceModel.ClientBase<CP_CW_8392.UI.SwipeCollection.ISwipeCollectionService>, CP_CW_8392.UI.SwipeCollection.ISwipeCollectionService {
        
        public SwipeCollectionServiceClient() {
        }
        
        public SwipeCollectionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SwipeCollectionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SwipeCollectionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SwipeCollectionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartCollectingSwipes() {
            base.Channel.StartCollectingSwipes();
        }
        
        public System.Threading.Tasks.Task StartCollectingSwipesAsync() {
            return base.Channel.StartCollectingSwipesAsync();
        }
        
        public CP_CW_8392.UI.SwipeCollection.Terminal[] GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public System.Threading.Tasks.Task<CP_CW_8392.UI.SwipeCollection.Terminal[]> GetStatusAsync() {
            return base.Channel.GetStatusAsync();
        }
        
        public CP_CW_8392.UI.SwipeCollection.Swipe[] GetAllSwipes() {
            return base.Channel.GetAllSwipes();
        }
        
        public System.Threading.Tasks.Task<CP_CW_8392.UI.SwipeCollection.Swipe[]> GetAllSwipesAsync() {
            return base.Channel.GetAllSwipesAsync();
        }
    }
}
